# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='logo',
            field=models.FileField(blank=True, upload_to='restaurant_logo/'),
        ),
    ]
