# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0003_customer_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
