# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0004_restaurants_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
